// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const batchUpdateBalances = `-- name: BatchUpdateBalances :exec
UPDATE balances AS b
SET
    available = b.available + updates.avail_delta,
    locked = b.locked + updates.lock_delta,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::uuid[]) as u_id,
        unnest($2::text[]) as a_sym,
        unnest($3::bigint[]) as avail_delta,
        unnest($4::bigint[]) as lock_delta
) AS updates
WHERE b.user_id = updates.u_id AND b.asset_symbol = updates.a_sym
`

type BatchUpdateBalancesParams struct {
	UserIds     []uuid.UUID `json:"user_ids"`
	Assets      []string    `json:"assets"`
	AvailDeltas []int64     `json:"avail_deltas"`
	LockDeltas  []int64     `json:"lock_deltas"`
}

func (q *Queries) BatchUpdateBalances(ctx context.Context, arg BatchUpdateBalancesParams) error {
	_, err := q.db.Exec(ctx, batchUpdateBalances,
		arg.UserIds,
		arg.Assets,
		arg.AvailDeltas,
		arg.LockDeltas,
	)
	return err
}

type CreateLedgerEntriesParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	AssetSymbol   string    `json:"asset_symbol"`
	Amount        int64     `json:"amount"`
	BalanceType   string    `json:"balance_type"`
	ReferenceType string    `json:"reference_type"`
	ReferenceID   uuid.UUID `json:"reference_id"`
}

const createLedgerEntry = `-- name: CreateLedgerEntry :exec
INSERT INTO ledger_entries (
    id, user_id, asset_symbol, amount, balance_type, reference_type, reference_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateLedgerEntryParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	AssetSymbol   string    `json:"asset_symbol"`
	Amount        int64     `json:"amount"`
	BalanceType   string    `json:"balance_type"`
	ReferenceType string    `json:"reference_type"`
	ReferenceID   uuid.UUID `json:"reference_id"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createLedgerEntry,
		arg.ID,
		arg.UserID,
		arg.AssetSymbol,
		arg.Amount,
		arg.BalanceType,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	return err
}

const ensureBalancesExist = `-- name: EnsureBalancesExist :exec
INSERT INTO balances (user_id, asset_symbol, available, locked, updated_at)
SELECT
    unnest($1::uuid[]),
    unnest($2::text[]),
    0, 0, NOW()
ON CONFLICT (user_id, asset_symbol) DO NOTHING
`

type EnsureBalancesExistParams struct {
	UserIds []uuid.UUID `json:"user_ids"`
	Assets  []string    `json:"assets"`
}

func (q *Queries) EnsureBalancesExist(ctx context.Context, arg EnsureBalancesExistParams) error {
	_, err := q.db.Exec(ctx, ensureBalancesExist, arg.UserIds, arg.Assets)
	return err
}

const getBalancesByUser = `-- name: GetBalancesByUser :many
SELECT asset_symbol, available, locked
FROM balances
WHERE user_id = $1
`

type GetBalancesByUserRow struct {
	AssetSymbol string `json:"asset_symbol"`
	Available   int64  `json:"available"`
	Locked      int64  `json:"locked"`
}

func (q *Queries) GetBalancesByUser(ctx context.Context, userID uuid.UUID) ([]GetBalancesByUserRow, error) {
	rows, err := q.db.Query(ctx, getBalancesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBalancesByUserRow
	for rows.Next() {
		var i GetBalancesByUserRow
		if err := rows.Scan(&i.AssetSymbol, &i.Available, &i.Locked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBalances = `-- name: ListAllBalances :many
SELECT user_id, asset_symbol, available, locked
FROM balances
`

type ListAllBalancesRow struct {
	UserID      uuid.UUID `json:"user_id"`
	AssetSymbol string    `json:"asset_symbol"`
	Available   int64     `json:"available"`
	Locked      int64     `json:"locked"`
}

func (q *Queries) ListAllBalances(ctx context.Context) ([]ListAllBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAllBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBalancesRow
	for rows.Next() {
		var i ListAllBalancesRow
		if err := rows.Scan(
			&i.UserID,
			&i.AssetSymbol,
			&i.Available,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalanceLock = `-- name: UpdateBalanceLock :one
UPDATE balances
SET
    available = available - $1,
    locked = locked + $1,
    updated_at = NOW()
WHERE user_id = $2
    AND asset_symbol = $3
    AND available >= $1
RETURNING available, locked
`

type UpdateBalanceLockParams struct {
	Amount      int64     `json:"amount"`
	UserID      uuid.UUID `json:"user_id"`
	AssetSymbol string    `json:"asset_symbol"`
}

type UpdateBalanceLockRow struct {
	Available int64 `json:"available"`
	Locked    int64 `json:"locked"`
}

func (q *Queries) UpdateBalanceLock(ctx context.Context, arg UpdateBalanceLockParams) (UpdateBalanceLockRow, error) {
	row := q.db.QueryRow(ctx, updateBalanceLock, arg.Amount, arg.UserID, arg.AssetSymbol)
	var i UpdateBalanceLockRow
	err := row.Scan(&i.Available, &i.Locked)
	return i, err
}

const updateBalanceUnlock = `-- name: UpdateBalanceUnlock :one
UPDATE balances
SET
    available = available + $1,
    locked = locked - $1,
    updated_at = NOW()
WHERE user_id = $2
    AND asset_symbol = $3
    AND locked >= $1
RETURNING available, locked
`

type UpdateBalanceUnlockParams struct {
	Amount      int64     `json:"amount"`
	UserID      uuid.UUID `json:"user_id"`
	AssetSymbol string    `json:"asset_symbol"`
}

type UpdateBalanceUnlockRow struct {
	Available int64 `json:"available"`
	Locked    int64 `json:"locked"`
}

func (q *Queries) UpdateBalanceUnlock(ctx context.Context, arg UpdateBalanceUnlockParams) (UpdateBalanceUnlockRow, error) {
	row := q.db.QueryRow(ctx, updateBalanceUnlock, arg.Amount, arg.UserID, arg.AssetSymbol)
	var i UpdateBalanceUnlockRow
	err := row.Scan(&i.Available, &i.Locked)
	return i, err
}

const upsertBalance = `-- name: UpsertBalance :one
INSERT INTO balances (user_id, asset_symbol, available, locked, updated_at)
VALUES ($1, $2, $3, 0, NOW())
ON CONFLICT (user_id, asset_symbol)
DO UPDATE SET
    available = balances.available + EXCLUDED.available,
    updated_at = NOW()
RETURNING user_id, asset_symbol, available, locked, updated_at
`

type UpsertBalanceParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AssetSymbol string    `json:"asset_symbol"`
	Available   int64     `json:"available"`
}

func (q *Queries) UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, upsertBalance, arg.UserID, arg.AssetSymbol, arg.Available)
	var i Balance
	err := row.Scan(
		&i.UserID,
		&i.AssetSymbol,
		&i.Available,
		&i.Locked,
		&i.UpdatedAt,
	)
	return i, err
}
