// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateLedgerEntries implements pgx.CopyFromSource.
type iteratorForCreateLedgerEntries struct {
	rows                 []CreateLedgerEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLedgerEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLedgerEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].AssetSymbol,
		r.rows[0].Amount,
		r.rows[0].BalanceType,
		r.rows[0].ReferenceType,
		r.rows[0].ReferenceID,
	}, nil
}

func (r iteratorForCreateLedgerEntries) Err() error {
	return nil
}

func (q *Queries) CreateLedgerEntries(ctx context.Context, arg []CreateLedgerEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ledger_entries"}, []string{"id", "user_id", "asset_symbol", "amount", "balance_type", "reference_type", "reference_id"}, &iteratorForCreateLedgerEntries{rows: arg})
}
