// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type OrderSide string

const (
	OrderSideBUY  OrderSide = "BUY"
	OrderSideSELL OrderSide = "SELL"
)

func (e *OrderSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSide(s)
	case string:
		*e = OrderSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSide: %T", src)
	}
	return nil
}

type NullOrderSide struct {
	OrderSide OrderSide `json:"order_side"`
	Valid     bool      `json:"valid"` // Valid is true if OrderSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSide), nil
}

type Order struct {
	ID                uuid.UUID    `json:"id"`
	Price             string       `json:"price"`
	Quantity          int32        `json:"quantity"`
	Side              OrderSide    `json:"side"`
	RemainingQuantity int32        `json:"remaining_quantity"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type Trade struct {
	ID             int32         `json:"id"`
	BuyerOrderID   uuid.NullUUID `json:"buyer_order_id"`
	SellerOrderID  uuid.NullUUID `json:"seller_order_id"`
	ExecutionPrice string        `json:"execution_price"`
	Quantity       int32         `json:"quantity"`
	ExecutedAt     sql.NullTime  `json:"executed_at"`
}
