// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderSide string

const (
	OrderSideBUY  OrderSide = "BUY"
	OrderSideSELL OrderSide = "SELL"
)

func (e *OrderSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSide(s)
	case string:
		*e = OrderSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSide: %T", src)
	}
	return nil
}

type NullOrderSide struct {
	OrderSide OrderSide `json:"order_side"`
	Valid     bool      `json:"valid"` // Valid is true if OrderSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSide), nil
}

type OrderStatus string

const (
	OrderStatusNEW       OrderStatus = "NEW"
	OrderStatusPLACED    OrderStatus = "PLACED"
	OrderStatusPARTIAL   OrderStatus = "PARTIAL"
	OrderStatusFILLED    OrderStatus = "FILLED"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
	OrderStatusREJECTED  OrderStatus = "REJECTED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Balance struct {
	UserID      uuid.UUID        `json:"user_id"`
	AssetSymbol string           `json:"asset_symbol"`
	Available   int64            `json:"available"`
	Locked      int64            `json:"locked"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type LedgerEntry struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	AssetSymbol   string           `json:"asset_symbol"`
	Amount        int64            `json:"amount"`
	BalanceType   string           `json:"balance_type"`
	ReferenceType string           `json:"reference_type"`
	ReferenceID   uuid.UUID        `json:"reference_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID                uuid.UUID        `json:"id"`
	UserID            uuid.UUID        `json:"user_id"`
	Price             int64            `json:"price"`
	Quantity          int64            `json:"quantity"`
	Side              OrderSide        `json:"side"`
	RemainingQuantity int64            `json:"remaining_quantity"`
	Status            OrderStatus      `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type Outbox struct {
	ID          uuid.UUID        `json:"id"`
	Type        string           `json:"type"`
	Payload     []byte           `json:"payload"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type Trade struct {
	ID             uuid.UUID        `json:"id"`
	BuyerOrderID   uuid.UUID        `json:"buyer_order_id"`
	SellerOrderID  uuid.UUID        `json:"seller_order_id"`
	TakerUserID    uuid.UUID        `json:"taker_user_id"`
	MakerUserID    uuid.UUID        `json:"maker_user_id"`
	ExecutionPrice int64            `json:"execution_price"`
	Quantity       int64            `json:"quantity"`
	ExecutedAt     pgtype.Timestamp `json:"executed_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
