// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
DELETE FROM orders WHERE id = $1
`

func (q *Queries) CancelOrder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, price, quantity, side, remaining_quantity
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, price, quantity, side, remaining_quantity, created_at
`

type CreateOrderParams struct {
	ID                pgtype.UUID `json:"id"`
	Price             int64       `json:"price"`
	Quantity          int32       `json:"quantity"`
	Side              OrderSide   `json:"side"`
	RemainingQuantity int32       `json:"remaining_quantity"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Price,
		arg.Quantity,
		arg.Side,
		arg.RemainingQuantity,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.RemainingQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    buyer_order_id, seller_order_id, execution_price, quantity
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, buyer_order_id, seller_order_id, execution_price, quantity, executed_at
`

type CreateTradeParams struct {
	BuyerOrderID   pgtype.UUID `json:"buyer_order_id"`
	SellerOrderID  pgtype.UUID `json:"seller_order_id"`
	ExecutionPrice int64       `json:"execution_price"`
	Quantity       int32       `json:"quantity"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.BuyerOrderID,
		arg.SellerOrderID,
		arg.ExecutionPrice,
		arg.Quantity,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.BuyerOrderID,
		&i.SellerOrderID,
		&i.ExecutionPrice,
		&i.Quantity,
		&i.ExecutedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, price, quantity, side, remaining_quantity, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.RemainingQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentTrades = `-- name: GetRecentTrades :many
SELECT id, buyer_order_id, seller_order_id, execution_price, quantity, executed_at FROM trades
ORDER BY executed_at DESC
LIMIT $1
`

func (q *Queries) GetRecentTrades(ctx context.Context, limit int32) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getRecentTrades, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.BuyerOrderID,
			&i.SellerOrderID,
			&i.ExecutionPrice,
			&i.Quantity,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOrdersBySide = `-- name: ListActiveOrdersBySide :many
SELECT id, price, quantity, side, remaining_quantity, created_at FROM orders
WHERE side = $1 and remaining_quantity > 0
ORDER BY
    CASE WHEN $1 = 'BUY' THEN price END DESC,
    CASE WHEN $2 = 'SELL' THEN price END ASC,
    created_at ASC
`

type ListActiveOrdersBySideParams struct {
	Side    OrderSide   `json:"side"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) ListActiveOrdersBySide(ctx context.Context, arg ListActiveOrdersBySideParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listActiveOrdersBySide, arg.Side, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Price,
			&i.Quantity,
			&i.Side,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderQuantity = `-- name: UpdateOrderQuantity :one
UPDATE orders
SET remaining_quantity = $2
WHERE id = $1
RETURNING id, price, quantity, side, remaining_quantity, created_at
`

type UpdateOrderQuantityParams struct {
	ID                pgtype.UUID `json:"id"`
	RemainingQuantity int32       `json:"remaining_quantity"`
}

func (q *Queries) UpdateOrderQuantity(ctx context.Context, arg UpdateOrderQuantityParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderQuantity, arg.ID, arg.RemainingQuantity)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.RemainingQuantity,
		&i.CreatedAt,
	)
	return i, err
}
