// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET status = 'CANCELLED'
WHERE id = $1 AND status IN ('NEW', 'PLACED', 'PARTIAL')
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, user_id, price, quantity, side, remaining_quantity, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, price, quantity, side, remaining_quantity, status, created_at
`

type CreateOrderParams struct {
	ID                uuid.UUID        `json:"id"`
	UserID            uuid.UUID        `json:"user_id"`
	Price             int64            `json:"price"`
	Quantity          int64            `json:"quantity"`
	Side              OrderSide        `json:"side"`
	RemainingQuantity int64            `json:"remaining_quantity"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Price,
		arg.Quantity,
		arg.Side,
		arg.RemainingQuantity,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    id, buyer_order_id, seller_order_id, taker_user_id, maker_user_id, execution_price, quantity
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type CreateTradeParams struct {
	ID             uuid.UUID `json:"id"`
	BuyerOrderID   uuid.UUID `json:"buyer_order_id"`
	SellerOrderID  uuid.UUID `json:"seller_order_id"`
	TakerUserID    uuid.UUID `json:"taker_user_id"`
	MakerUserID    uuid.UUID `json:"maker_user_id"`
	ExecutionPrice int64     `json:"execution_price"`
	Quantity       int64     `json:"quantity"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.ID,
		arg.BuyerOrderID,
		arg.SellerOrderID,
		arg.TakerUserID,
		arg.MakerUserID,
		arg.ExecutionPrice,
		arg.Quantity,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, price, quantity, side, remaining_quantity, status, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentTrades = `-- name: GetRecentTrades :many
SELECT id, buyer_order_id, seller_order_id, taker_user_id, maker_user_id, execution_price, quantity, executed_at FROM trades
ORDER BY executed_at DESC
LIMIT $1
`

func (q *Queries) GetRecentTrades(ctx context.Context, limit int32) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getRecentTrades, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.BuyerOrderID,
			&i.SellerOrderID,
			&i.TakerUserID,
			&i.MakerUserID,
			&i.ExecutionPrice,
			&i.Quantity,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOrdersBySide = `-- name: ListActiveOrdersBySide :many
SELECT id, user_id, price, quantity, side, remaining_quantity, status, created_at FROM orders
WHERE side = $1 and remaining_quantity > 0
ORDER BY
    CASE WHEN $1 = 'BUY' THEN price END DESC,
    CASE WHEN $1 = 'SELL' THEN price END ASC,
    created_at ASC
`

func (q *Queries) ListActiveOrdersBySide(ctx context.Context, side OrderSide) ([]Order, error) {
	rows, err := q.db.Query(ctx, listActiveOrdersBySide, side)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Price,
			&i.Quantity,
			&i.Side,
			&i.RemainingQuantity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderQuantity = `-- name: UpdateOrderQuantity :one
UPDATE orders
SET remaining_quantity = $2,
    status = $3
WHERE id = $1
RETURNING id, user_id, price, quantity, side, remaining_quantity, status, created_at
`

type UpdateOrderQuantityParams struct {
	ID                uuid.UUID   `json:"id"`
	RemainingQuantity int64       `json:"remaining_quantity"`
	Status            OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderQuantity(ctx context.Context, arg UpdateOrderQuantityParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderQuantity, arg.ID, arg.RemainingQuantity, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const updateOrderStatusesBatch = `-- name: UpdateOrderStatusesBatch :exec
UPDATE orders
SET status = val.status::order_status
FROM (
    SELECT
        unnest($1::uuid[]) as id,
        unnest($2::text[]) as status
) as val
WHERE orders.id = val.id
`

type UpdateOrderStatusesBatchParams struct {
	Ids      []uuid.UUID `json:"ids"`
	Statuses []string    `json:"statuses"`
}

func (q *Queries) UpdateOrderStatusesBatch(ctx context.Context, arg UpdateOrderStatusesBatchParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatusesBatch, arg.Ids, arg.Statuses)
	return err
}
