// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addOutboxEvent = `-- name: AddOutboxEvent :exec
INSERT INTO outbox (id, type, payload)
VALUES ($1, $2, $3)
`

type AddOutboxEventParams struct {
	ID      uuid.UUID `json:"id"`
	Type    string    `json:"type"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) AddOutboxEvent(ctx context.Context, arg AddOutboxEventParams) error {
	_, err := q.db.Exec(ctx, addOutboxEvent, arg.ID, arg.Type, arg.Payload)
	return err
}

const fetchUnprocessedEvents = `-- name: FetchUnprocessedEvents :many
SELECT id, type, payload, created_at, processed_at FROM outbox
WHERE processed_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) FetchUnprocessedEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, fetchUnprocessedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE outbox
SET processed_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}
