// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOutboxEvent(ctx context.Context, arg AddOutboxEventParams) error
	BatchUpdateBalances(ctx context.Context, arg BatchUpdateBalancesParams) error
	CancelOrder(ctx context.Context, id uuid.UUID) error
	CreateLedgerEntries(ctx context.Context, arg []CreateLedgerEntriesParams) (int64, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (uuid.UUID, error)
	CreateTradesBatch(ctx context.Context, arg CreateTradesBatchParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	EnsureBalancesExist(ctx context.Context, arg EnsureBalancesExistParams) error
	FetchUnprocessedEvents(ctx context.Context, limit int32) ([]Outbox, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetRecentTrades(ctx context.Context, limit int32) ([]Trade, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListActiveOrdersBySide(ctx context.Context, side OrderSide) ([]Order, error)
	ListAllBalances(ctx context.Context) ([]ListAllBalancesRow, error)
	MarkEventProcessed(ctx context.Context, id uuid.UUID) error
	MarkEventsProcessedBatch(ctx context.Context, dollar_1 []uuid.UUID) error
	UpdateBalanceLock(ctx context.Context, arg UpdateBalanceLockParams) (UpdateBalanceLockRow, error)
	UpdateBalanceUnlock(ctx context.Context, arg UpdateBalanceUnlockParams) (UpdateBalanceUnlockRow, error)
	UpdateOrderQuantity(ctx context.Context, arg UpdateOrderQuantityParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateOrderStatusesBatch(ctx context.Context, arg UpdateOrderStatusesBatchParams) error
	UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (Balance, error)
}

var _ Querier = (*Queries)(nil)
