// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelOrder(ctx context.Context, id uuid.UUID) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetRecentTrades(ctx context.Context, limit int32) ([]Trade, error)
	ListActiveOrdersBySide(ctx context.Context, arg ListActiveOrdersBySideParams) ([]Order, error)
	UpdateOrderQuantity(ctx context.Context, arg UpdateOrderQuantityParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
